# -*- coding: utf-8 -*-
"""lab2_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgpVji0sMJMKtbR1YFlS4jyciqojv_7Z
"""



"""# Matplotlib

# Numpy

# List
"""

my_list = [1,2,3,4,5,6,7,8,9,10]
print(my_list)

list_sum = sum(my_list)
list_max = max(my_list)
list_min = min(my_list)

print(f"Sum of the list: {list_sum}")
print(f"Maximum value in the list: {list_max}")
print(f"Minimum value in the list: {list_min}")

my_list.append(11)
print(my_list)

my_list.remove(10)
print(my_list)

my_list.sort()
print(my_list)

my_list.sort(reverse=True)
print(my_list)

"""# Tuple"""

my_tuple = ("apple", "banana", "cherry", "date", "elderberry")
print(my_tuple)

print('Second Element',my_tuple[1])
print('Last Element',my_tuple[-1])

my_list = list(my_tuple)
my_list[2] = 'orange'
print('Modified List',my_list)

my_tuple = tuple(my_list)
print('Modified Tuple',my_tuple)

"""# Set"""

set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print("Set 1:", set1)
print("Set 2:", set2)

# Common elements
print("Common elements:", set1.intersection(set2))

# Unique elements in set1
print("Unique elements in Set 1:", set1.difference(set2))

# Unique elements in set2
print("Unique elements in Set 2:", set2.difference(set1))

# All unique elements
print("All unique elements:", set1.symmetric_difference(set2))

# Union of sets
print("Union of Set 1 and Set 2:", set1.union(set2))

# Add an element to set1
set1.add(9)
print("Set 1 after adding 9:", set1)

# Remove an element from set1
set1.remove(1)
print("Set 1 after removing 1:", set1)

"""# Dictionary"""

student_marks = {
    "Alice": 95,
    "Bob": 88,
    "Charlie": 76,
    "David": 92,
    "Eve": 85
}
print(student_marks)

student_marks["Bob"] = 90
print("Dictionary after updating Bob's marks:", student_marks)